Migrate to eslint and use kebab-case for filenames
nomiclabs/hardhat-ignition pull request #39
Opened 2021-07-01 16:40 UTC by fvictorio

Depends on #38.

2021-07-04 14:03 UTC, filippetroviccc requested changes

2021-07-04 14:03 UTC, filippetroviccc commented on packages/ignition-core/src/services/utils/logging/index.ts
> +/* eslint-enable @typescript-eslint/naming-convention */
Same as above.

2021-07-04 22:26 UTC, alcuadrado commented on packages/ignition-core/src/services/types/migration.ts
> +/* eslint-enable @typescript-eslint/naming-convention */
This is interesting. 

Shouldn't this be something like:

```ts
export enum FileGenerationType {
  USAGE = "usage"
  // ...
}
```

2021-07-05 16:26 UTC, fvictorio commented on packages/ignition-core/src/services/types/migration.ts
> +/* eslint-enable @typescript-eslint/naming-convention */
Yes, you can use a different convention for enums, but I would prefer using the same config as we use in Hardhat, with enum values like the one in @alcuadrado's snippet.

2021-07-14 16:16 UTC, merged